//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocamerMsySite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option_sejour
    {
        public int id { get; set; }
        public Nullable<int> sejour_id { get; set; }
        public Nullable<int> option_id { get; set; }
        public Nullable<int> quantite { get; set; }
        public Nullable<int> duree { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual Sejour Sejour { get; set; }
    }
}
